image: gradle:jdk17

stages:
  - test
  - lint
  - build

gradle_test:
  stage: test
  script:
    - gradle test

ktlint:
  stage: lint
  script:
    - gradle ktlintCheck

gradle_build:
  stage: build
  script:
    - gradle build
