image: gradle:7.6.1-jdk17

stages:
  - test
  - lint
  - build

gradle_test:
  stage: test
  script:
    - gradle :loki-core:test
    - gradle :loki-core:test

ktlint:
  stage: lint
  script:
    - gradle ktlintCheck

gradle_build:
  stage: build
  script:
    - gradle :loki-core:build
    - gradle :loki-core:server
